### PR TITLE
update ansible_distribution=RedHat

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by metmajer** [comment]
Hi @countryHick. Thanks for the PR! Willing to roll out this change to the other roles in https://github.com/dynatrace/Dynatrace-Ansible as well?

**Comment by ghost** [comment]
there are 3 need changing that i found - collector and webserver-agent also have PRs open -- i'm using my forks in my dynatrace-ansible fork as well for all 3 :) :+1:

**Comment by metmajer** [comment]
:+1: those are all that needed to be changed. Thanks again for the fix!

**Comment by ghost** [comment]
Pleasure!    it’s nice to see vendor built/support repos like this :)

**Pull request merged**
