### PR TITLE
Fixes around installer reliability.

### PR DESCRIPTION
**Pull request by soniah**
I changed to having installer download directly onto target server;
you may want to add logic to do both old cached method and new
direct download method.

several fixes:
- dynatrace_collector_user
- download installer on target machine
- fix template path errors
- add checksum to downloaded installer
- ansible_os_family

### CODE REVIEW

**Comment by metmajer** [comment]
@soniah: your PR contains a bunch of changes. Most of them have been resolved in previous commits. I am curious on our take of around this: while I fancy the idea of downloading the installer from the remote machine, you miss out on using the `files` directory to provide a specific installer artifact. Would you say this is not needed? I am not sure yet if this applies to all our users though.

Do you want to rebase your PR based on the current master?

**Comment by soniah** [comment]
Not sure what you mean, as I can specify a specific artifact in my remote
download.

Motivation was slow/unreliable networks (both at home and corporate). I'm
building on AWS, so it makes more sense to download from AWS. My later
fixes (I haven't done PR's) I've added md5 checkums to get_url as well as a
checksum param, to make sure I'm getting a good file.

**Comment by metmajer** [comment]
I mean that your code change doesn't allow a user to do an offline installation by placing installer artifacts in the respective roles' `files` directory (and possibly run it all from a USB stick) as you had removed this portion from your codebase. In restricted customer environments this scenario makes sense and speed- and reliability-wise, you couldn't get any better than that. Then, have the remote machines download the installer when it is not available in the `files` directory would be the optimal solution from my perspective. This should only require a small change to how it works at the moment.

I am very much interested in the md5 check. Do you want to provide a PR for #6?

**Comment by metmajer** [comment]
@soniah: any comment on this?

**Comment by soniah** [comment]
No, I've been smashed delivering a project :-(

**Comment by metmajer** [comment]
@soniah: I have changed the download behavior as follows in all Ansible roles: the installer is downloaded on the remote machine if it has not been provided in the `files` directory in commit c2a84faf690182318280843cfbfd53b3b2be23fc. The changes have been pushed to Ansible Galaxy and are present in the [v6.3](https://github.com/Dynatrace/Dynatrace-Collector-Ansible/releases/tag/v6.3) release.

**Pull request closed without merging**
